FORMAT: 1A
HOST: http://pwaforum.apiblueprint.org/

# Forum API

API for PWA discussion forum.

# Data Structures

## Accounts (object)
+ userid: 1 (number, required)
+ username: user1 (string, required)
+ firstname: xxx (string)
+ lastname: xxx (string)
+ email: xxx@xxx.com (string, required)
+ password: pswd (string, required)
+ confirmpasswd: pswd (string, required)
+ ismale: true (boolean)
+ phone: 123456789 (string)
+ country: xxx (string)
+ city: xxx (string)
+ age: 30 (string)
+ interests: xxx (string)
+ info: xxx (string)

## Themes (object)
+ themeid: 1 (number, required)
+ themename: theme (string, required)
+ description: xxx (string)
+ createdby: user (string, required)
+ createdat: `2014-11-11T08:40:51.620Z` (string)

## Posts (object)
+ postid: 1 (number, required)
+ content: xxx (string, required)
+ themeid: 1 (number, required)
+ addedby: user (string, required)
+ addedat: `2014-11-11T08:40:51.620Z` (string)

## Responses (object)
+ responseid: 1 (number, required)
+ rcontent: xxx (string, required)
+ rootid: 1 (number, required)
+ addedby: user (string, required)
+ addedat: `2014-11-11T08:40:51.620Z` (string)

# Accounts [/accounts]

## Retrieve All Accounts [GET]
+ Response 200 (application/json)
    + Attributes (array[Accounts])

## Add new Account [POST]
+ Request (application/json)
    + Attributes([Accounts])
+ Response 201 (application/json)
    + Headers
    
            Location: /accounts/2
            
    + Body
    
            + Attributes
                + userid: 2 (number, required)
                + username: user2 (string, required)
                + email: xxx@xxx.com (string, required)
                + password: psw (string, required)
                + confirmpasswd: psw (string, required)
                + ismale: true (boolean)

## Concrete Account [/accounts/{id}]

+ Parameters
    + id

### Retrieve Account[GET]
+ Response 200 (application/json)
    + Attributes (Accounts)

### Edit Account [PUT]
+ Request (application/json)
    + Attributes([Accounts])
+ Response 204 

### Delete Account [DELETE]
+ Response 204

# Themes [/themes]

## Retrieve All Themes [GET]
+ Response 200 (application/json)
    + Attributes (array[Themes])

## Add new Theme [POST]
+ Request (application/json)
    + Attributes([Themes])
+ Response 201 (application/json)
    + Headers
    
            Location: /themes/2
            
    + Body
    
            + Attributes
                + themeid: 2 (number, required)
                + themename: theme2 (string, required)
                + createdby: user (string, required)
                + createdat: `2014-11-11T08:40:51.620Z` (string)

## Concrete Theme [/theme/{id}]

+ Parameters
    + id

### Retrieve Theme[GET]
+ Response 200 (application/json)
    + Attributes (Themes)

### Edit Theme [PUT]
+ Request (application/json)
    + Attributes([Themes])
+ Response 204 

### Delete Theme [DELETE]
+ Response 204

# Posts [/posts]

## Retrieve All Posts [GET]
+ Response 200 (application/json)
    + Attributes (array[Posts])

## Add new Post [POST]
+ Request (application/json)
    + Attributes([Posts])
+ Response 201 (application/json)
    + Headers
    
            Location: /posts/2
            
    + Body
    
            + Attributes
                + postid: 2 (number, required)
                + content: xxx (string, required)
                + themeid: 1 (number, required)
                + addedby: user (string, required)
                + addedat: `2014-11-11T08:40:51.620Z` (string)

## Concrete Post [/posts/{id}]

+ Parameters
    + id

### Retrieve Post[GET]
+ Response 200 (application/json)
    + Attributes (Posts)

### Edit Post [PUT]
+ Request (application/json)
    + Attributes([Posts])
+ Response 204 

### Delete Post[DELETE]
+ Response 204

# Responses [/responses]

## Retrieve All Responses [GET]
+ Response 200 (application/json)
    + Attributes (array[Responses])

## Add new Response [POST]
+ Request (application/json)
    + Attributes([Responses])
+ Response 201 (application/json)
    + Headers
    
            Location: /responses/2
            
    + Body
    
            + Attributes
                + responseid: 2 (number, required)
                + rcontent: xxx (string, required)
                + rootid: 1 (number, required)
                + addedby: user (string, required)
                + addedat: `2014-11-11T08:40:51.620Z` (string)

## Concrete Response [/responses/{id}]

+ Parameters
    + id

### Retrieve Response[GET]
+ Response 200 (application/json)
    + Attributes (Responses)

### Edit Response [PUT]
+ Request (application/json)
    + Attributes(Responses)
+ Response 204 

### Delete Response[DELETE]
+ Response 204